# Generated by Django 4.2.2 on 2023-10-30 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_programconfig_max_workers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programconfig",
            name="python_version",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="programconfig",
            name="max_workers",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="programconfig",
            name="min_workers",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
    ]
